export interface AchievementInfo {
    icon: string;
    tag: string;
    target: number;
    popup: string;
}

export const ACHIEVEMENTS: { [key: string]: AchievementInfo } = {
    'training-completed': {
        icon: 'dummy-01',
        tag: 'objectives',
        target: 0,
        popup: 'Congratulations!<br>You have completed your training!',
    },
    'first-blood': {
        icon: 'dungeon-01',
        tag: 'objectives',
        target: 0,
        popup: 'Congratulations!<br>You have completed your first dungeon level!',
    },
    'scenario-forgotten-ruins-completed': {
        icon: 'dungeon-01',
        tag: '',
        target: 0,
        popup: 'Congratulations!<br>You have completed the Forgotten Ruins!',
    },
    'scenario-cursed-swamp-completed': {
        icon: 'dungeon-01',
        tag: '',
        target: 0,
        popup: 'Congratulations!<br>You have completed the Cursed Swamp!',
    },
    'scenario-demonic-forest-completed': {
        icon: 'dungeon-01',
        tag: '',
        target: 0,
        popup: 'Congratulations!<br>You have completed the Demonic Forest!',
    },
    'scenario-orcs-camp-completed': {
        icon: 'dungeon-01',
        tag: '',
        target: 0,
        popup: 'Congratulations!<br>You have completed the Orcs Camp!',
    },
    'scenario-dragons-lair-completed': {
        icon: 'dungeon-01',
        tag: '',
        target: 0,
        popup: 'Congratulations!<br>You have completed the Dragon\'s Lair!',
    },
    'kill-5-slimes': {
        icon: 'quest-kill-5-slimes',
        tag: 'Kills',
        target: 5,
        popup: 'You have killed the Slime',
    },
    'kill-10-slimes': {
        icon: 'quest-kill-10-slimes',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Slime',
    },
    'kill-10-rats': {
        icon: 'quest-kill-10-rats',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Rat',
    },
    'kill-10-toads': {
        icon: 'quest-kill-10-toads',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Toad',
    },
    'kill-10-snakes': {
        icon: 'quest-kill-10-snakes',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Snake',
    },
    'kill-20-rats': {
        icon: 'quest-kill-20-rats',
        tag: 'Kills',
        target: 20,
        popup: 'You have killed the Giant Rat',
    },
    'kill-10-fleas': {
        icon: 'quest-kill-10-fleas',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Giant Flea',
    },
    'kill-20-bats': {
        icon: 'quest-kill-20-bats',
        tag: 'Kills',
        target: 20,
        popup: 'You have killed the bat',
    },
    'kill-10-skeletons': {
        icon: 'quest-kill-10-skeletons',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Skeleton',
    },
    'kill-10-zombies': {
        icon: 'quest-kill-10-zombies',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Zombie',
    },
    'kill-10-goblins': {
        icon: 'quest-kill-10-goblins',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Nasty Goblin',
    },
    'kill-10-demons': {
        icon: 'quest-kill-10-demons',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Demon',
    },
    'kill-5-trolls': {
        icon: 'quest-kill-5-trolls',
        tag: 'Kills',
        target: 5,
        popup: 'You have killed the North Troll',
    },
    'kill-5-demonic-boars': {
        icon: 'quest-kill-5-demonic-boars',
        tag: 'Kills',
        target: 5,
        popup: 'You have killed the Demonic Boar',
    },
    'kill-5-demonic-wolfs': {
        icon: 'quest-kill-5-demonic-wolfs',
        tag: 'Kills',
        target: 5,
        popup: 'You have killed the Demonic Wolf',
    },
    'kill-5-orc-necromancers': {
        icon: 'quest-kill-5-orc-necromancers',
        tag: 'Kills',
        target: 5,
        popup: 'You have killed the Orc Necromancer',
    },
    'kill-5-wendigo': {
        icon: 'quest-kill-5-wendigo',
        tag: 'Kills',
        target: 5,
        popup: 'You have killed the Wendigo',
    },
    'kill-10-griffins': {
        icon: 'quest-kill-10-griffins',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Griffin',
    },
    'kill-10-manticores': {
        icon: 'quest-kill-10-manticores',
        tag: 'Kills',
        target: 10,
        popup: 'You have killed the Manticore',
    },
    'kill-20-orcs': {
        icon: 'quest-kill-20-orcs',
        tag: 'Kills',
        target: 20,
        popup: 'You have killed the Orc',
    },
    'artifact-01': {
        icon: 'quest-find-artifact-01',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Cursed Goblet',
    },
    'artifact-02': {
        icon: 'quest-find-artifact-02',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Sinister Skull',
    },
    'artifact-03': {
        icon: 'quest-find-artifact-03',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Seekers Book',
    },
    'artifact-04': {
        icon: 'quest-find-artifact-04',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Amulet of Ultimate Evil',
    },
    'artifact-05': {
        icon: 'quest-find-artifact-05',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Runes of Chaos',
    },
    'artifact-06': {
        icon: 'quest-find-artifact-06',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Scroll of Eternal Darkness',
    },
    'artifact-07': {
        icon: 'quest-find-artifact-07',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Orb of Dragon King',
    },
    'artifact-08': {
        icon: 'quest-find-artifact-08',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Bloody Goblet',
    },
    'artifact-09': {
        icon: 'quest-find-artifact-09',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Eldritch Heart',
    },
    'artifact-10': {
        icon: 'quest-find-artifact-10',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Magic Chest',
    },
    'artifact-11': {
        icon: 'quest-find-artifact-11',
        tag: 'Artifacts',
        target: 0,
        popup: 'You have found the Golden Apple',
    },
    'kill-grim-reaper': {
        icon: 'quest-kill-grim-reaper',
        tag: 'Objectives',
        target: 0,
        popup: 'You have defeated the Grim Reaper!',
    },
    'kill-hydra': {
        icon: 'quest-kill-hydra',
        tag: 'Objectives',
        target: 0,
        popup: 'You have defeated the Hydra!',
    },
    'kill-forest-witch': {
        icon: 'quest-kill-forest-witch',
        tag: 'Objectives',
        target: 0,
        popup: 'You have defeated the Forest Witch!',
    },
    'kill-orc-commander': {
        icon: 'quest-kill-orc-commander',
        tag: 'Objectives',
        target: 0,
        popup: 'You have defeated the Orc Commander!',
    },
    'save-princess': {
        icon: 'quest-save-princess',
        tag: 'Objectives',
        target: 0,
        popup: 'Congratulations!<br>You have defeated the Dragon and saved the Princess!',
    },
};
